---
title: "Untitled"
author: "Willem Feijen"
date: "16 februari 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bupaR)
library(edeaR)
library(processmonitR)
library(plotluck)
library(DiagrammeR)
#library(DiagrammeRsvg)

csvLog<-read.table("../3.0 RefundProcess.csv",header = TRUE, sep = ";",na = c("n.v.t.","onbekend"))
csvLog$status = "complete"
csvLog$activity_instance = 1:nrow(csvLog)
csvLog$timestamp<-as.POSIXct(strptime(csvLog$Complete.timestamp, "%d-%m-%Y  %H:%M"))
eventLog1<-eventlog(csvLog,
					case_id = "Order.Nr.",
					activity_id = "Status",
					activity_instance_id = "activity_instance",
					lifecycle_id = "status",
					timestamp = "timestamp",
					resource_id = "Employee"
)

refundIssued<-n_cases((gefilteredeEventLog<-filter_activity_presence(eventLog1,activities = c("Refund issued","Special refund issued"),method ="one_of")))
aantalzonderProductReceived<-n_cases(gefilteredeEventLog<-filter_precedence(gefilteredeEventLog,antecedents=c("Product received"), consequents=c("Refund issued","Special refund issued"),precedence_type = "eventually_follows",filter_method ="one_of",reverse=TRUE))
paste0("Er zijn ",refundIssued, " gevallen met refunds. Daarvan is van ",aantalzonderProductReceived," geen product ontvangen voor de refund")

debugonce(frequency)
x<-frequency("relative")
print(x)
str(x)
```


```{r}
#debugonce(GetBasicNodes)
map<-enrichedProcessMap(gefilteredeEventLog, aggregationInstructions = c(frequency("relative")),render = F )
map%>%render_graph()
```

