---
title: "Untitled"
author: "Willem Feijen"
date: "16 februari 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bupaR)
library(edeaR)
library(processmonitR)
library(plotluck)
library(DiagrammeR)
library(data.table)
#library(DiagrammeRsvg)

csvLog<-read.table("../3.0 RefundProcessVoorNarekenen.csv",header = TRUE, sep = ";",na = c("n.v.t.","onbekend"))
csvLog$status = "complete"
csvLog$activity_instance = 1:nrow(csvLog)
csvLog$startmoment<-as.POSIXct(strptime(csvLog$startmoment, "%d-%m-%Y  %H:%M"))
csvLog$eindmoment<-as.POSIXct(strptime(csvLog$eindmoment, "%d-%m-%Y  %H:%M"))


lengteLogIngelezen<-nrow(csvLog)
kolomNamen<-colnames(csvLog)
csvLog$activity_instance = 1:nrow(csvLog)
csvLogStart<-data.table(csvLog)
csvLogStart$timeStamp<-csvLogStart$startmoment
csvLogStart$status<-"start"
csvLogEind<-csvLog
csvLogEind$timeStamp<-csvLogEind$eindmoment
csvLogEind$status<-"eind"
csvLog<-rbind(csvLogStart,csvLogEind)
rm(csvLogStart,csvLogEind)


csvLog<-na.omit(csvLog,cols=c("OrderNr","Status","timeStamp"))
```
We houden: `r nrow(csvLog)` regels van de `r lengteLogVoorVerwijderen` regels uit de oorspronkelijke log over, ofwel `r round(nrow(csvLog)*100/lengteLogVoorVerwijderen,digits = 2)`%.

#Gevonden kolomkoppen:
```{r echo=FALSE, warning=T, error=T, message=T}
colnames(csvLog)
```

#Omzetten naar een processmining Log 
```{r echo=FALSE, warning=FALSE}
if (!("Werknemer" %in% colnames(csvLog))){csvLog$Werknemer<-NA}
eventLog.Base<-eventlog(csvLog,
        case_id = "OrderNr",
        activity_id = "Status",
        activity_instance_id = "activity_instance",
        lifecycle_id = "status",
        timestamp = "timeStamp",
        resource_id = "Employee"
    )
```
# Map met frequency
```{r}
agregationInst = list( frequency(value = "absolute", columnName = "xxx") )
map<-enrichedProcessMap(eventLog.Base, aggregationInstructions = agregationInst )
map %>%
    processmapR::color_activities( column = "xxx",
                      colorCaption = "black",
                      colorUpperbound = "deeppink",
                      colorLowerbound = "green1") %>%
    label_activities(columns =c("activity_name","xxx")) %>%
          color_transitions(column = "xxx",
          colorCaption = "black",
          colorUpperbound = "deeppink",
          colorLowerbound = "darkgreen") %>%
    label_transitions(columns = c("xxx")) %>% 
    render_graph()

map.nodes <- map %>% get_node_df()
map.edges <- map %>% get_edge_df()
```
# Map met performance
```{r}
agregationInst = list( performance(FUN = mean, columnName = "xxx"))
map<-enrichedProcessMap(eventLog.Base, aggregationInstructions = agregationInst )
map %>%
    processmapR::color_activities( column = "xxx",
                      colorCaption = "black",
                      colorUpperbound = "deeppink",
                      colorLowerbound = "green1") %>%
    label_activities(columns =c("activity_name","xxx")) %>%
          color_transitions(column = "xxx",
          colorCaption = "black",
          colorUpperbound = "deeppink",
          colorLowerbound = "darkgreen") %>%
    label_transitions(columns = c("xxx")) %>% 
    render_graph()

map.nodes <- map %>% get_node_df()
map.edges <- map %>% get_edge_df()
```
# Map met aggregate
```{r}

agregationInst = list(columnAggregate( FUN = mean, columnNameIn = "RandomWaarde1", columnNameOut = "xxx1", edgeOperation = "to"),columnAggregate( FUN = mean, columnNameIn = "RandomWaarde2", columnNameOut = "xxx2", edgeOperation = "from")
                      )
map<-enrichedProcessMap(eventLog.Base, aggregationInstructions = agregationInst )
map.nodes <- map %>% get_node_df()
map.edges <- map %>% get_edge_df()
map %>%
    processmapR::color_activities( column = "xxx2",
                      colorCaption = "black",
                      colorUpperbound = "deeppink",
                      colorLowerbound = "green1") %>%
    label_activities(columns =c("activity_name","xxx2")) %>%
          color_transitions(column = "xxx2",
          colorCaption = "black",
          colorUpperbound = "deeppink",
          colorLowerbound = "darkgreen") %>%
    label_transitions(columns = c("xxx2")) %>% 
    render_graph()


```
```{r}
map %>% get_node_df()

map %>%
    processmapR::color_activities( column = "xxx2",
                      colorCaption = "black",
                      colorUpperbound = "deeppink",
                      colorLowerbound = "green1") %>%
    label_activities(columns =c("activity_name")) %>%
          color_transitions(column = "xxx2",
          colorCaption = "black",
          colorUpperbound = "deeppink",
          colorLowerbound = "darkgreen") %>%
    label_transitions(columns = c("xxx2")) %>% 
    render_graph()
```

```{r}
map %>%
    color_activities( column = "xxx2",
                      colorCaption = "black",
                      colorUpperbound = "lightblue",
                      colorLowerbound = "green1") %>%
    label_activities(columns =c("activity_name","xxx1","xxx2")) %>%
    color_transitions(column = "xxx2",
          colorCaption = "black",
          colorUpperbound = "deeppink",
          colorLowerbound = "darkgreen") %>%
    label_transitions(columns = c("xxx1","xxx2")) %>% 
    render_graph()
```

```{r}
map %>%
    color_activities( column = "xxx2",
                      colorCaption = "black",
                      colorUpperbound = "yellow",
                      colorLowerbound = "green1") %>%
    label_activities(columns =c()) %>%
    color_transitions(column = "xxx2",
          colorCaption = "black",
          colorUpperbound = "deeppink",
          colorLowerbound = "darkgreen") %>%
    label_transitions(columns = c()) %>% 
    render_graph()
```


```{r}

```

