---
title: "Untitled"
author: "Willem Feijen"
date: "16 februari 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bupaR)
library(edeaR)
library(processmonitR)
library(plotluck)
library(DiagrammeR)
library(data.table)
#library(DiagrammeRsvg)

csvLog<-read.table("../3.0 RefundProcessVoorNarekenen.csv",header = TRUE, sep = ";",na = c("n.v.t.","onbekend"))
csvLog$status = "complete"
csvLog$activity_instance = 1:nrow(csvLog)
csvLog$startmoment<-as.POSIXct(strptime(csvLog$startmoment, "%d-%m-%Y  %H:%M"))
csvLog$eindmoment<-as.POSIXct(strptime(csvLog$eindmoment, "%d-%m-%Y  %H:%M"))


lengteLogIngelezen<-nrow(csvLog)
kolomNamen<-colnames(csvLog)
csvLog$activity_instance = 1:nrow(csvLog)
csvLogStart<-data.table(csvLog)
csvLogStart$timeStamp<-csvLogStart$startmoment
csvLogStart$status<-"start"
csvLogEind<-csvLog
csvLogEind$timeStamp<-csvLogEind$eindmoment
csvLogEind$status<-"eind"
csvLog<-rbind(csvLogStart,csvLogEind)
rm(csvLogStart,csvLogEind)


csvLog<-na.omit(csvLog,cols=c("OrderNr","Status","timeStamp"))
```
We houden: `r nrow(csvLog)` regels van de `r lengteLogVoorVerwijderen` regels uit de oorspronkelijke log over, ofwel `r round(nrow(csvLog)*100/lengteLogVoorVerwijderen,digits = 2)`%.

#Gevonden kolomkoppen:
```{r echo=FALSE, warning=T, error=T, message=T}
colnames(csvLog)
```

#Omzetten naar een processmining Log 
```{r echo=FALSE, warning=FALSE}
if (!("Werknemer" %in% colnames(csvLog))){csvLog$Werknemer<-NA}
eventLog.Base<-eventlog(csvLog,
        case_id = "OrderNr",
        activity_id = "Status",
        activity_instance_id = "activity_instance",
        lifecycle_id = "status",
        timestamp = "timeStamp",
        resource_id = "Employee"
    )

```



```{r}
agregationInst = list(columnAggregate( FUN = mean, columnNameIn = "RandomWaarde1", columnNameOut = "xxx1", edgeOperation = "to"),columnAggregate( FUN = max, columnNameIn = "RandomWaarde2", columnNameOut = "xxx2", edgeOperation = "from"))
map<-enrichedProcessMap(eventLog.Base, aggregationInstructions = agregationInst )
map%>%render_graph()
map.nodes <- map %>% get_node_df()
map.edges <- map %>% get_edge_df()
```
```{r}
color_activities <- function( diagrammerProcessMap,
                             column,
                             colorCaption  = "black",
                             colorUpperbound = "gray100",
                             colorLowerbound= "gray50"){
    diagrammerProcessMap %>%
      rescale_node_attrs(
        node_attr_from = !!column,
        to_lower_bound = colorLowerbound,
        to_upper_bound = colorUpperbound,
        node_attr_to = fillcolor ) %>%
      rescale_node_attrs(
        node_attr_from = !!column,
        to_lower_bound = colorCaption,
        to_upper_bound = colorCaption,
        node_attr_to = fontcolor) %>%
      rescale_node_attrs(
        node_attr_from = !!column,
        to_lower_bound = colorCaption,
        to_upper_bound = colorCaption,
        node_attr_to = color) 
}

label_activities <- function( diagrammerProcessMap,
                             columns =c("activity_name")
                             ){
    if (length(columns) > 1)
        diagrammerProcessMap$nodes_df$tempVarGjdasflx <-  apply( get_node_df(diagrammerProcessMap)[ , columns ] , 1 , paste , collapse = "\n\r" )
    else if (length(columns) == 1)
        diagrammerProcessMap$nodes_df$tempVarGjdasflx <-  get_node_df(diagrammerProcessMap)[, columns[1]]
    else #no columns
        diagrammerProcessMap$nodes_df$tempVarGjdasflx <- ""

    diagrammerProcessMap %>%
        mutate_node_attrs(label = tempVarGjdasflx)
}

map %>% get_node_df()

gevuldeMap <- map %>%
                color_activities( column = "xxx2",
                                  colorCaption = "black",
                                  colorUpperbound = "red4",
                                  colorLowerbound = "green1") %>%
                label_activities(columns =c("activity_name","xxx1","xxx2"))

gevuldeMap %>% render_graph()

gevuldeMap <- map %>%
                color_activities( column = "xxx2",
                                  colorCaption = "black",
                                  colorUpperbound = "red4",
                                  colorLowerbound = "green1") %>%
                label_activities(columns =c("activity_name"))

gevuldeMap %>% render_graph()

gevuldeMap <- map %>%
                color_activities( column = "xxx2",
                                  colorCaption = "black",
                                  colorUpperbound = "red4",
                                  colorLowerbound = "green1") %>%
                label_activities(columns =c())

gevuldeMap %>% render_graph()

```
```{r}
color_edges <- function( diagrammerProcessMap,
                             captionColumns = "",
                             colorCaption,
                             column,
                             colorUpperbound,
                             colorLowerbound){
    diagrammerProcessMap %>%
  rescale_edge_attrs(
    edge_attr_from = !!column,
    to_lower_bound = colorLowerbound,
    to_upper_bound = colorUpperbound,
    edge_attr_to = fillcolor ) %>%
  rescale_edge_attrs(
    edge_attr_from = !!column,
    to_lower_bound = colorCaption,
    to_upper_bound = colorCaption,
    edge_attr_to = fontcolor) %>%
  rescale_edge_attrs(
    edge_attr_from = !!column,
    to_lower_bound = colorCaption,
    to_upper_bound = colorCaption,
    edge_attr_to = color) %>%
  mutate_edge_attrs(label = activity_name)
}

map %>% get_node_df()

gevuldeMap <- color_edges(map, 
                              column = "xxx2",
                              colorCaption = "red4",
                              colorUpperbound = "gray50",
                              colorLowerbound = "gray100")

gevuldeMap %>% render_graph()

cols <- c("id","label","style")
x <-  apply( map.nodes[ , cols ] , 1 , paste , collapse = " " )#paste(list(map.nodes$id,map.nodes$label,map.nodes$style,map.nodes$penwidth),sep = " ")
x


```

```{r}

```

